name: Frontend Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug: confirm the files CI actually sees
      - name: Show workspace files
        run: |
          pwd
          ls -la

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Be explicit so caching finds the lock file
          cache-dependency-path: package-lock.json

      # If a lockfile exists, use npm ci; otherwise fallback to install
      - name: Install (ci if lockfile, else install)
        run: |
          if [ -f frontend-skillfolio/package-lock.json ]; then
            npm ci --prefix frontend;
          else
            echo "No package-lock.json found; falling back to npm install"
            npm install
          fi

      - name: Run tests
        run: npm run test:ci
