name: Frontend Tests

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./skillfolio-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: |
          echo "PWD (repo root):"
          pwd
          echo "--- list repo root ---"
          ls -la
          echo "--- list app dir ---"
          ls -la skillfolio-frontend || true
          echo "--- lockfile probe ---"
          find . -maxdepth 3 -name "package-lock.json" -print

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # or '24' if you want to match local

      - name: Install
        run: npm ci

      - name: Test (CI)
        run: npm run test:ci
