name: Frontend Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./skillfolio-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Prove where the lockfile actually is (from repo root)
      - name: Show files (debug)
        run: |
          pwd
          echo "---- list repo root ----"
          ls -la
          echo "---- list app dir ----"
          ls -la skillfolio-frontend || true
          echo "--- lockfile probe ---"
          find . -maxdepth 3 -name "package-lock.json" -print

      - name: Use Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '24'        # LTS (you can use '22' or '24' too)
          # cache: 'npm'
          # MUST be relative to REPO ROOT and match the *actual* path exactly:
          # cache-dependency-path: SKILLFOLIO-FRONTEND/skillfolio-frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm run test:ci
