name: Frontend Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./skillfolio-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug: confirm we are in the nested folder and lockfile exists
      - name: Show files
        run: |
          pwd
          ls -la
          echo "---- repo root ----"
          ls -la ..
          echo "---- lockfile? ----"
          test -f package-lock.json && echo "Found package-lock.json" || (echo "NO LOCKFILE HERE" && exit 1)

      - name: Use Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # IMPORTANT: point to the lockfile in the nested folder
          cache-dependency-path: skillfolio-frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm run test:ci
