name: Frontend Tests

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./skillfolio-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: skillfolio-frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Test (CI)
        env:
          CI: true
        run: npm run test:ci
